// Generated by gencpp from file dmsgs/HeadCommand.msg
// DO NOT EDIT!


#ifndef DMSGS_MESSAGE_HEADCOMMAND_H
#define DMSGS_MESSAGE_HEADCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dmsgs
{
template <class ContainerAllocator>
struct HeadCommand_
{
  typedef HeadCommand_<ContainerAllocator> Type;

  HeadCommand_()
    : pitch(0.0)
    , yaw(0.0)
    , pitchSpeed(0.0)
    , yawSpeed(0.0)  {
    }
  HeadCommand_(const ContainerAllocator& _alloc)
    : pitch(0.0)
    , yaw(0.0)
    , pitchSpeed(0.0)
    , yawSpeed(0.0)  {
  (void)_alloc;
    }



   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _pitchSpeed_type;
  _pitchSpeed_type pitchSpeed;

   typedef float _yawSpeed_type;
  _yawSpeed_type yawSpeed;





  typedef boost::shared_ptr< ::dmsgs::HeadCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dmsgs::HeadCommand_<ContainerAllocator> const> ConstPtr;

}; // struct HeadCommand_

typedef ::dmsgs::HeadCommand_<std::allocator<void> > HeadCommand;

typedef boost::shared_ptr< ::dmsgs::HeadCommand > HeadCommandPtr;
typedef boost::shared_ptr< ::dmsgs::HeadCommand const> HeadCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dmsgs::HeadCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dmsgs::HeadCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dmsgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'dmsgs': ['/home/ubuntu/dancer-workspace/workspaces/lib/src/dmsgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dmsgs::HeadCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dmsgs::HeadCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dmsgs::HeadCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dmsgs::HeadCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmsgs::HeadCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmsgs::HeadCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dmsgs::HeadCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a80ab250ebcaff2070441c8a32284d96";
  }

  static const char* value(const ::dmsgs::HeadCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa80ab250ebcaff20ULL;
  static const uint64_t static_value2 = 0x70441c8a32284d96ULL;
};

template<class ContainerAllocator>
struct DataType< ::dmsgs::HeadCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dmsgs/HeadCommand";
  }

  static const char* value(const ::dmsgs::HeadCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dmsgs::HeadCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pitch\n\
float32 yaw\n\
float32 pitchSpeed\n\
float32 yawSpeed\n\
\n\
";
  }

  static const char* value(const ::dmsgs::HeadCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dmsgs::HeadCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.pitchSpeed);
      stream.next(m.yawSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeadCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dmsgs::HeadCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dmsgs::HeadCommand_<ContainerAllocator>& v)
  {
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitchSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.pitchSpeed);
    s << indent << "yawSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.yawSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DMSGS_MESSAGE_HEADCOMMAND_H
